name: bangla_converter
description: Flutter package for converting Bangla Number to English Number or vice versa, with Bangla and English date conversion support.
version: 2.0.1
homepage: https://github.com/Pritom-Chaki/bangla_converter
repository: https://github.com/Pritom-Chaki/bangla_converter
issue_tracker: https://github.com/Pritom-Chaki/bangla_converter/issues
topics:
  - bangla
  - bengali
  - localization
  - converter
  - formatter

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
